# Generated by Django 4.2.29 on 2026-09-12 06:01

from django.db import migrations


class Migration(migrations.Migration):
    """
    Drop the presentation metadata, now that it lives in the database it describes.

    Every field of ColumnMetaData moved into presentation_schema.columns, so the whole model goes.
    TableMetaData stays: its other four fields are Mathesar's own bookkeeping rather than anything
    about how the data looks -- data_file points at a DataFile here, import_verified is about an
    import, and the two attnums record what Mathesar did to a table -- so only the two that moved
    are removed.

    manage.py migrate_column_metadata copied what was here; it goes with them, having nothing left
    to read.
    """

    dependencies = [
        ('mathesar', '0017_columnmetadata_duration_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemetadata',
            name='column_order',
        ),
        migrations.RemoveField(
            model_name='tablemetadata',
            name='record_summary_template',
        ),
        migrations.DeleteModel(
            name='ColumnMetaData',
        ),
    ]
