# Generated by Django 4.2.29 on 2026-09-13 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Let a user be an agent somebody set going.

    An agent is a user with an owner rather than a model of its own, so that everything that
    already knows how to name a user, pick one into a User column and attribute a write to one
    goes on working without being taught about agents.

    The two constraints are the design: a name is only unique among one owner's agents, so two
    people sharing a Mathesar can each have a "Claude"; and an agent is never a superuser,
    because it borrows its owner's reach into the databases but administering Mathesar is not
    a thing to be delegated.
    """

    dependencies = [
        ('mathesar', '0018_remove_tablemetadata_column_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_model',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'full_name'), name='agent_name_unique_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('is_superuser', True), ('owner__isnull', False), _negated=True), name='agent_is_not_superuser'),
        ),
    ]
