# Generated by Django 4.2.29 on 2026-09-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Remember which agents have been issued a certificate, and until when.

    Enough to show on the page and to name when revoking, and no more: the certificate lives
    on the appliance and its password is kept nowhere at all, so one whose password was lost
    is reissued rather than recovered.
    """

    dependencies = [
        ('mathesar', '0019_user_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cert_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cert_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cert_serial',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
