export const DB_TYPES = {
  ARRAY: '_array',
  BIGINT: 'bigint',
  BIT: 'bit',
  BIT_VARYING: 'bit varying',
  BOOLEAN: 'boolean',
  BOX: 'box',
  BYTEA: 'bytea',
  CHAR: '"char"',
  CHARACTER_VARYING: 'character varying',
  CHARACTER: 'character',
  CIDR: 'cidr',
  CIRCLE: 'circle',
  COMPOSITE: '_composite',
  DATE: 'date',
  DATEMULTIRANGE: 'datemultirange',
  DATERANGE: 'daterange',
  DECIMAL: 'decimal',
  DOUBLE_PRECISION: 'double precision',
  ENUM: '_enum',
  INET: 'inet',
  INT4MULTIRANGE: 'int4multirange',
  INT4RANGE: 'int4range',
  INT8MULTIRANGE: 'int8multirange',
  INT8RANGE: 'int8range',
  INTEGER: 'integer',
  INTERVAL: 'interval',
  JSON: 'json',
  JSONB: 'jsonb',
  LINE: 'line',
  LSEG: 'lseg',
  MACADDR: 'macaddr',
  MACADDR8: 'macaddr8',
  MONEY: 'money',
  MSAR__EMAIL: 'mathesar_types.email',
  MSAR__FILE: 'mathesar_types.file',
  MSAR__MATHESAR_JSON_ARRAY: 'mathesar_types.mathesar_json_array',
  MSAR__MATHESAR_JSON_OBJECT: 'mathesar_types.mathesar_json_object',
  MSAR__MATHESAR_MONEY: 'mathesar_types.mathesar_money',
  MSAR__MULTICURRENCY_MONEY: 'mathesar_types.multicurrency_money',
  MSAR__URI: 'mathesar_types.uri',
  NAME: 'name',
  NUMERIC: 'numeric',
  NUMMULTIRANGE: 'nummultirange',
  NUMRANGE: 'numrange',
  OID: 'oid',
  PATH: 'path',
  POINT: 'point',
  POLYGON: 'polygon',
  REAL: 'real',
  REGCLASS: 'regclass',
  SMALLINT: 'smallint',
  TEXT: 'text',
  TIME_WITH_TZ: 'time with time zone',
  TIME_WITHOUT_TZ: 'time without time zone',
  TIMESTAMP_WITH_TZ: 'timestamp with time zone',
  TIMESTAMP_WITHOUT_TZ: 'timestamp without time zone',
  TSMULTIRANGE: 'tsmultirange',
  TSRANGE: 'tsrange',
  TSTZMULTIRANGE: 'tstzmultirange',
  TSTZRANGE: 'tstzrange',
  TSVECTOR: 'tsvector',
  UUID: 'uuid',
  XML: 'xml',
};
